// <auto-generated />
namespace AdmApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _170120 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_170120));
        
        string IMigrationMetadata.Id
        {
            get { return "201701202138439_170120"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
